sonar.projectKey=mifisc-orga_SQS-VerkehrsApp-Projekt
sonar.organization=mifisc-orga
sonar.sources=backend/sqs-verkehrsapp/src/main/java,frontend/src
sonar.tests=backend/sqs-verkehrsapp/src/test/java
sonar.java.binaries=backend/sqs-verkehrsapp/target/classes
sonar.java.test.binaries=backend/sqs-verkehrsapp/target/test-classes
