sonar.projectKey=mifisc-orga_SQS-VerkehrsApp-Projekt
sonar.organization=mifisc-orga
sonar.sources=backend/sqs-verkehrsapp/src/main/java,frontend/src
sonar.tests=backend/sqs-verkehrsapp/src/test/java,frontend/tests
sonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/tests/**/*.spec.ts
sonar.exclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/tests/**/*.spec.ts,**/coverage.ts

sonar.java.binaries=backend/sqs-verkehrsapp/target/classes
sonar.java.test.binaries=backend/sqs-verkehrsapp/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=backend/sqs-verkehrsapp/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,frontend/coverage-e2e/lcov.info

sonar.qualitygate.wait=true